name: shoppingapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_auth_token: ^1.0.5
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  flutter_bloc: ^8.1.5
  smooth_page_indicator: ^1.1.0
  dartz: ^0.10.1
  gettext: ^1.2.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
