// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Idyn8QbL7tHFWPIO5URpezK59RT7sNk',
    appId: '1:108556569857:web:45d9c98d92ab9b92939f00',
    messagingSenderId: '108556569857',
    projectId: 'e-app-62857',
    authDomain: 'e-app-62857.firebaseapp.com',
    storageBucket: 'e-app-62857.appspot.com',
    measurementId: 'G-SDXZPCJ5TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIR-vRSdI-JKhKn6GZpBUVdL_wCmoXpxQ',
    appId: '1:108556569857:android:1a28c337c1dd4b46939f00',
    messagingSenderId: '108556569857',
    projectId: 'e-app-62857',
    storageBucket: 'e-app-62857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABt5AeegqXfurKGLI7r9aGfV0GOSYyU2Y',
    appId: '1:108556569857:ios:bbf9ee9b3374abbe939f00',
    messagingSenderId: '108556569857',
    projectId: 'e-app-62857',
    storageBucket: 'e-app-62857.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABt5AeegqXfurKGLI7r9aGfV0GOSYyU2Y',
    appId: '1:108556569857:ios:bbf9ee9b3374abbe939f00',
    messagingSenderId: '108556569857',
    projectId: 'e-app-62857',
    storageBucket: 'e-app-62857.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
